### ISSUE TITLE
Error when running `npx create-codeceptjs`

### ISSUE THREAD

**Issue by PeterNgTr** [codeceptjs/create-codeceptjs#11]
I just cloned the repo then executed this command `npx create-codeceptjs`, it raised error like this.

```js
Creating CodeceptJS project in /Users/thanhnguyen/Desktop/create-codeceptjs

Powered by Playwright engine
package.json found, adding codeceptjs dependencies & scripts into it
(node:3284) UnhandledPromiseRejectionWarning: TypeError: deps.flat is not a function
    at createCodecept (/Users/thanhnguyen/.npm/_npx/3284/lib/node_modules/create-codeceptjs/index.js:158:22)
    at Object.<anonymous> (/Users/thanhnguyen/.npm/_npx/3284/lib/node_modules/create-codeceptjs/index.js:87:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at findNodeScript.then.existing (/Users/thanhnguyen/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
(node:3284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pablopaul** [comment]
Dont clone the repo and the command in the repo root folder but run it in a existing project which already have a package.json or to create a completely new project with `npx create-codeceptjs my-new-project`.

IMHO this issue can be closed @DavertMik
