### ISSUE TITLE
"codecept:demo" fails for all engines which are not Playwright

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/create-codeceptjs#9]
because examples repo expects playwright helper.

**Comment by DavertMik** [comment]
yes, that's true, they should use a different config file. Thank you!

**Comment by PeterNgTr** [comment]
I got the error using the default Playwright engine

```
MBP-Thanh-Home:create-codeceptjs thanhnguyen$ npm run codecept:demo

> create-codeceptjs@0.1.2 codecept:demo /Users/thanhnguyen/Desktop/create-codeceptjs
> codeceptjs run --steps -c node_modules/@codeceptjs/examples

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/Users/thanhnguyen/Desktop/create-codeceptjs/node_modules/@codeceptjs/examples'
    at Object.lstatSync (fs.js:841:3)
    at getTestRoot (/usr/local/lib/node_modules/codeceptjs/lib/command/utils.js:20:20)
    at Command.module.exports (/usr/local/lib/node_modules/codeceptjs/lib/command/run.js:19:20)
    at Command.listener (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:182:13)
    at Command.parseArgs (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:654:12)
    at Command.parse (/usr/local/lib/node_modules/codeceptjs/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/codeceptjs/bin/codecept.js:138:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-codeceptjs@0.1.2 codecept:demo: `codeceptjs run --steps -c node_modules/@codeceptjs/examples`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the create-codeceptjs@0.1.2 codecept:demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thanhnguyen/.npm/_logs/2020-07-15
```

**Comment by pablopaul** [comment]
@PeterNgTr you should not run `npx create-codeceptjs` in its own repo :)

**Comment by DavertMik** [comment]
Fixed this
